version: "3.3"
services:
    webserver:
      image: nginx:alpine
      container_name: bank-account-validator-webserver
      working_dir: /application/public
      volumes:
          - .:/application/public
          - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: compose/php-fpm
      container_name: bank-account-validator-php-fpm
      working_dir: /application/public
      volumes:
        - .:/application/public
        - ./compose/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

